[workspace]
resolver = "2"
members = ["status_lib", "status", "usr/bin/release"]

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["amkisko"]
license = "MIT"
repository = "https://github.com/amkisko/status-cli.rs"
homepage = "https://github.com/amkisko/status-cli.rs"
documentation = "https://docs.rs/status_lib"
keywords = ["status", "cli", "statuspage", "incident"]
categories = ["command-line-utilities", "development-tools"]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
type_complexity = "warn"
too_many_arguments = "warn"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
panic = "abort"
